/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: NASA Astromaterials 3D (https://sketchfab.com/Astromaterials3D)
license: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
source: https://sketchfab.com/3d-models/antarctic-meteorite-sample-lar-1232632-9518395c58084c6f883d903daa886460
title: Antarctic Meteorite Sample LAR 12326,32
*/

import { Float, PresentationControls, useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'
import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import { getRadiusNorm } from 'utils'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
  }
  materials: {
    material_1: THREE.MeshStandardMaterial
  }
}

const METEORITE_MODEL_RADIUS = 0.03606162561534413

const MeteoriteModel = React.memo<GroupProps>((props) => {
  const { nodes, materials } = useGLTF(
    '/models/meteorite/scene.gltf',
  ) as unknown as GLTFResult

  return (
    <group dispose={null} rotation={[Math.PI / 14, 0, -Math.PI / 2]} {...props}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.material_1}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials.material_1}
      />
    </group>
  )
})

export type MeteoriteProps = {
  isPresentationMode: boolean
}

export const Meteorite = React.memo<MeteoriteProps>(
  ({ isPresentationMode }) => {
    const scale = getRadiusNorm(METEORITE_MODEL_RADIUS)

    return (
      <Float speed={isPresentationMode ? undefined : 0}>
        <PresentationControls
          enabled={isPresentationMode}
          snap
          speed={2}
          polar={[-Infinity, Infinity]}
          azimuth={[-Infinity, Infinity]}
          config={{ mass: 10, tension: 200, friction: 40 }}
        >
          <MeteoriteModel scale={scale} />
        </PresentationControls>
      </Float>
    )
  },
)
